name: CI

on:
  # Compare the preceeding commit -> to the current commit of the main branch.
  # (Note: To compare changes between the current commit to the last pushed remote commit of the main branch set `since_last_remote_commit: true`)
  push:
    branches:
      - main
  # Compare the last commit of main -> to the current commit of a PR branch.
  # (Note: To compare changes between the current commit to the last pushed remote commit of a PR branch set `since_last_remote_commit: true`)
  pull_request:
    branches:
      - main

jobs:
  eslint:
    name: PHPCS Codesniffer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            +(app)/**

      - name: Install Package dependencies
        shell: bash
        run: yarn install
        if: env.GIT_DIFF

      - name: Check code style
        run: echo ${{env.GIT_DIFF}}
        if: env.GIT_DIFF && env.MATCHED_FILES