name: CI

on:
  # Compare the preceeding commit -> to the current commit of the main branch.
  # (Note: To compare changes between the current commit to the last pushed remote commit of the main branch set `since_last_remote_commit: true`)
  push:
    branches:
      - main
  # Compare the last commit of main -> to the current commit of a PR branch.
  # (Note: To compare changes between the current commit to the last pushed remote commit of a PR branch set `since_last_remote_commit: true`)
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2  # OR "2" -> To retrieve the preceding commit.


      - name: Create Standard Directory
        shell: bash
        run: mkdir demo

      - name: Install Coding Standard
        shell: bash
        working-directory: demo
        run: composer require "magento/magento-coding-standard"

      - name: Register Coding Standard
        shell: bash
        working-directory: demo
        run: vendor/bin/phpcs --config-set installed_paths ${{ github.workspace }}/demo/vendor/magento/magento-coding-standard,${{ github.workspace }}/demo/vendor/phpcompatibility/php-compatibility

      - name: Get Changed
        shell: bash
        working-directory: demo
        id: changed
        run: |
          'files=$(git diff --unified=0 --diff-filter=ACDMR HEAD^ HEAD | grep -v "^@@" | grep "^[+]" | grep -Ev "^(--- a/|\+\+\+ b/)")' >> $env:GITHUBOUTPUT
        

      - name: Changed Files.txt
        shell: bash
        id: cat-file
        run: echo ${{ steps.changed.outputs.files }}


